// In-memory PostgreSQL only. No connections to production or external APIs.
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const {PGlite}=await import(pathToFileURL(path.resolve(process.argv[2])).href);
const db=new PGlite();
const order='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000009';
try{
 await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');
 await db.exec(await readFile('supabase/orders-schema.sql','utf8'));
 await db.exec("create table wc_fulfilment(order_id uuid,ready_at timestamptz);create table wc_shipping_rules(match_name text,match_value text,effect_type text,active boolean);");
 await db.exec((await readFile('supabase/migrations/20260831000200_create_wc_order_activity.sql','utf8')).replace('create extension if not exists pgcrypto;',''));
 for(const f of ['20260907000100_delivery_cost_review.sql','20260907000200_delivery_invoice_gst.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 await db.query("insert into wc_orders(id,wix_order_id,shipping,currency) values($1,'fixture',100,'AUD')",[order]);
 const item=(await db.query("insert into wc_order_items(order_id,product_name,unit_price) values($1,'First product',110) returning id",[order])).rows[0].id;
 const unit=(await db.query('insert into wc_production_units(order_item_id,unit_index) values($1,1) returning id',[item])).rows[0].id;
 await db.query("update wc_delivery_reviews set state='packaging_required' where order_id=$1",[order]);
 await db.exec('grant all on wc_orders,wc_order_items,wc_production_units,wc_order_activity to authenticated;');
 const before=(await db.query('select to_jsonb(o) v from wc_orders o')).rows;
 await db.exec(await readFile('supabase/migrations/20260907000300_delivery_production_gate.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20260909000700_production_sanding.sql','utf8'));
 assert.deepEqual((await db.query('select to_jsonb(o) v from wc_orders o')).rows,before);
 const context=async()=>{
  const o=(await db.query('select updated_at from wc_orders where id=$1',[order])).rows[0];
  const r=(await db.query('select updated_at from wc_delivery_reviews where order_id=$1',[order])).rows[0];
  const items=(await db.query('select to_jsonb(i) v from wc_order_items i where order_id=$1',[order])).rows.map(r=>r.v);
  return [o.updated_at,JSON.stringify(items),'[]',r.updated_at];
 };
 const approve=async(reason='First manufacture')=>db.query('select wc_approve_delivery_without_quote($1,$2,$3,$4,$5,$6,$7,$8,$9)',[order,actor,reason,'key',10000,...await context()]);
 await db.exec('set role authenticated');
 await assert.rejects(db.query("update wc_production_units set production_status='Ready' where id=$1",[unit]),/permission denied/);
 await assert.rejects(db.query("insert into wc_production_units(order_item_id,unit_index,production_status) values($1,2,'Ready')",[item]),/permission denied/);
 await assert.rejects(db.query('delete from wc_production_units where id=$1',[unit]),/permission denied/);
 await db.query("update wc_production_units set production_comment='Local note',priority=1 where id=$1",[unit]);
 await assert.rejects(approve(),/permission denied/);
 await db.exec('reset role');
 await assert.rejects(approve(' '),/reason/);
 await approve();await approve();
 let r=(await db.query('select * from wc_delivery_reviews where order_id=$1',[order])).rows[0];
 assert.equal(r.state,'approved_without_quote');assert.equal(r.quote_attempted_at,null);assert.equal(r.approval.actor,actor);assert.equal(r.approval_history.length,1);
 assert.equal((await db.query('select wc_claim_delivery_review($1,$2) claimed',[order,actor])).rows[0].claimed,false);
 const move=async(ctx=null,id=unit)=>db.query('select wc_set_reviewed_production_status($1,$2,$3,$4,$5,$6,$7,$8,$9) activity',[order,id,'CNC',actor,'approved_without_quote',...(ctx||await context())]);
 const ctx=await context();await db.query("update wc_order_items set quantity=2 where id=$1",[item]);
 await assert.rejects(move(ctx),/Items changed/);
 assert.equal((await db.query('select production_status from wc_production_units where id=$1',[unit])).rows[0].production_status,'New');
 const other=(await db.query("insert into wc_orders(wix_order_id) values('other') returning id")).rows[0].id;
 const otherItem=(await db.query("insert into wc_order_items(order_id) values($1) returning id",[other])).rows[0].id;
 const otherUnit=(await db.query('insert into wc_production_units(order_item_id,unit_index) values($1,1) returning id',[otherItem])).rows[0].id;
 await assert.rejects(move(await context(),otherUnit),/does not belong/);
 const action=await move();assert.equal(action.rows[0].activity.new_status,'CNC');await move();
 assert.equal((await db.query('select count(*)::int n from wc_order_activity')).rows[0].n,1);
 await db.exec("alter table wc_order_activity add constraint fixture_note_failure check(new_status<>'Assembly')");
 await assert.rejects(db.query('select wc_set_reviewed_production_status($1,$2,$3,$4,$5,$6,$7,$8,$9)',[order,unit,'Assembly',actor,'approved_without_quote',...await context()]),/fixture_note_failure/);
 assert.equal((await db.query('select production_status from wc_production_units where id=$1',[unit])).rows[0].production_status,'CNC');
 await db.exec('alter table wc_order_activity drop constraint fixture_note_failure');
 const rulesCtx=await context();await db.exec("insert into wc_shipping_rules values('Hole',null,'No effect',true)");
 await assert.rejects(move(rulesCtx),/Rules changed/);await db.exec('delete from wc_shipping_rules');
 const reviewCtx=await context();await db.query('update wc_delivery_reviews set updated_at=clock_timestamp() where order_id=$1',[order]);await assert.rejects(move(reviewCtx),/Review changed/);
 const c=await context();
 await db.query('select wc_save_delivery_packages($1,$2,$3,$4,false,$5,$6)',[order,JSON.stringify([{package_name:'Measured',length_mm:100,width_mm:100,height_mm:100,weight_kg:1,contents:[]}]),'signature',actor,c[0],c[1]]);
 assert.equal((await db.query('select state from wc_delivery_reviews where order_id=$1',[order])).rows[0].state,'pending');
 await db.query('update wc_delivery_reviews set quote_attempted_at=now() where order_id=$1',[order]);await assert.rejects(approve(),/Unquoted/);
 assert.equal((await db.query('select count(*)::int n from wc_delivery_booking_exemptions')).rows[0].n,0);
 await db.query('select wc_set_reviewed_production_status($1,$2,$3,$4,$5,$6,$7,$8,$9)',[order,unit,'Sanding',actor,'within_target',...await context()]);
 assert.equal((await db.query('select production_status from wc_production_units where id=$1',[unit])).rows[0].production_status,'Sanding');
 assert.equal((await db.query("select count(*)::int n from wc_order_activity where new_status='Sanding'")).rows[0].n,1);
 await assert.rejects(db.query("update wc_production_units set production_status='Unknown'"),/check/);
 await db.exec('set role authenticated');
 await assert.rejects(db.query('select wc_set_reviewed_production_status($1,$2,$3,$4,$5,$6,$7,$8,$9)',[order,unit,'Sanding',actor,'within_target',...await context()]),/permission denied/);
 console.log('PASS: Sanding persists with audit; status constraints and service-only permissions preserved; existing delivery guards passed.');
}finally{await db.close();}
