import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const {PGlite}=await import(pathToFileURL(path.resolve(process.argv[2])).href);
const db=new PGlite();
try{
 await db.exec("create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;");
 await db.exec(await readFile('supabase/orders-schema.sql','utf8'));
 const order=(await db.query("insert into wc_orders(wix_order_id,order_number,currency) values('fixture','100','AUD') returning id")).rows[0].id;
 const makeItem=async(size='I',status='New')=>{const i=(await db.query("insert into wc_order_items(order_id,product_name,wix_options,catalog_reference) values($1,'Cart',jsonb_build_object('Size',$2::text),'{\"catalogItemId\":\"cart\"}') returning id",[order,size])).rows[0].id;
 const u=(await db.query('insert into wc_production_units(order_item_id,unit_index,production_status) values($1,1,$2) returning id',[i,status])).rows[0].id;return {i,u};};
 const ready=await makeItem('I','Ready'),a=await makeItem();
 await db.exec(await readFile('supabase/migrations/20260907000800_material_costing.sql','utf8'));
 const costs=async()=> (await db.query('select * from wc_product_costs order by unit_id')).rows;
 assert.equal((await costs()).length,1);assert.equal((await costs())[0].state,'materials_required');
 await db.exec('set role anon');await assert.rejects(db.query('select * from wc_materials'),/permission denied/);await db.exec('reset role');
 await assert.rejects(db.query("select wc_save_material(null,'MDF','sheet',11,true,null)"),/Authentication/);
 await db.exec("select set_config('test.actor','00000000-0000-4000-8000-000000000009',false)");
 let m=(await db.query("select wc_save_material(null,'MDF','sheet',null,true,null) m")).rows[0].m;
 const key=async id=>(await db.query('select wc_material_variant(i) k from wc_order_items i where id=$1',[id])).rows[0].k;
 const lines=[{material_id:m.id,quantity:1.5}];
 await db.query('select wc_save_material_profile($1,$2,$3,null)',[a.i,await key(a.i),lines]);
 assert.equal((await costs())[0].state,'price_required');
 m=(await db.query("select wc_save_material($1,'MDF','sheet',11,true,$2) m",[m.id,m.updated_at])).rows[0].m;
 const locked=(await costs())[0];assert.equal(Number(locked.total_gst),16.5);assert.equal(locked.snapshot.gst_inclusive,true);
 m=(await db.query("select wc_save_material($1,'MDF','sheet',22,true,$2) m",[m.id,m.updated_at])).rows[0].m;
 assert.deepEqual((await costs())[0],locked);
 const b=await makeItem();assert.equal(Number((await costs()).find(c=>c.unit_id===b.u).total_gst),33);
 assert.equal((await costs()).some(c=>c.unit_id===ready.u),false);
 const other=await makeItem('II');assert.equal((await costs()).find(c=>c.unit_id===other.u).state,'materials_required');
 const profile=(await db.query('select * from wc_material_profiles')).rows[0];
 await db.query('select wc_save_material_profile($1,$2,$3,$4)',[a.i,await key(a.i),[{material_id:m.id,quantity:2}],profile.updated_at]);
 assert.deepEqual((await costs()).find(c=>c.unit_id===a.u),locked);
 const c=await makeItem();assert.equal(Number((await costs()).find(x=>x.unit_id===c.u).total_gst),44);
 await assert.rejects(db.query('select wc_save_material_profile($1,$2,$3,null)',[a.i,await key(a.i),lines]),/Profile changed/);
 await db.query("update wc_order_items set wix_options='{\"Size\":\"III\"}' where id=$1",[a.i]);
 const report=(await db.query('select * from wc_costing_report()')).rows.map(r=>r.wc_costing_report);
 assert.equal(report.find(r=>r.unit_id===a.u).changed,true);assert.deepEqual((await costs()).find(x=>x.unit_id===a.u),locked);
 await db.exec('set role authenticated');await assert.rejects(db.query('update wc_product_costs set total_gst=0'),/permission denied/);await assert.rejects(db.query('select wc_calculate_material_item($1)',[a.i]),/permission denied/);await db.exec('reset role');
 const mixed=(await db.query("insert into wc_order_items(order_id,product_name,quantity,wix_options,catalog_reference) values($1,'Cart',2,'{\"Size\":\"I\"}','{\"catalogItemId\":\"cart\"}') returning id",[order])).rows[0].id;
 await db.query("insert into wc_production_units(order_item_id,unit_index,production_status) values($1,1,'Ready'),($1,2,'New')",[mixed]);
 assert.equal((await costs()).filter(x=>x.item_id===mixed).length,1);
 assert.equal((await db.query('select count(*)::int n from wc_material_prices')).rows[0].n,3);
 const free=(await db.query("select wc_save_material(null,'Offcut','piece',0,true,null) m")).rows[0].m;
 await assert.rejects(db.query('select wc_save_material_profile($1,$2,$3,null)',[other.i,await key(other.i),[{material_id:m.id,quantity:-1}]]),/Invalid/);
 await assert.rejects(db.query('select wc_save_material_profile($1,$2,$3,null)',[other.i,await key(other.i),[...lines,...lines]]),/Duplicate/);
 await db.query('select wc_save_material_profile($1,$2,$3,null)',[other.i,await key(other.i),[{material_id:m.id,quantity:1},{material_id:free.id,quantity:4}]]);
 assert.equal(Number((await costs()).find(x=>x.unit_id===other.u).total_gst),22);
 m=(await db.query("select wc_save_material($1,'MDF','sheet',22,false,$2) m",[m.id,m.updated_at])).rows[0].m;
 const archivedMaterialOrder=await makeItem('II');assert.equal((await costs()).find(x=>x.unit_id===archivedMaterialOrder.u).state,'price_required');
 await assert.rejects(db.query("select wc_save_material($1,'MDF','kg',22,true,$2)",[m.id,m.updated_at]),/Unit cannot change/);
 await assert.rejects(db.query("select wc_save_material(null,'Invalid','sheet','NaN'::numeric,true,null)"),/check constraint/);
 assert.deepEqual((await costs()).find(x=>x.unit_id===a.u),locked);
 console.log('PASS: GST snapshots, price history, profile changes, Ready and mixed quantities, automatic new-unit costing, missing data, exact variants, drift detection, RLS and stale guards');
}catch(e){console.error(e.message);process.exitCode=1;}finally{await db.close();}
