// Rehearse CNC sheet storage and RPCs with synthetic records only.
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {randomUUID} from 'node:crypto';

const {PGlite}=await import(pathToFileURL(path.resolve(process.argv[2])).href);
const db=new PGlite();
try{
 await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
 create function storage.foldername(path text) returns text[] language sql immutable as $$select string_to_array(path,'/')$$;
 create table public.wc_shipping_products(id uuid primary key, product_name text, product_type text);
 create table public.wc_materials(id uuid primary key, name text not null, unit text not null, active boolean not null default true);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
 alter table storage.objects enable row level security;
 grant usage on schema public,storage,auth to authenticated;
 grant select,insert,delete on storage.objects to authenticated;`);
 await db.exec(await readFile('supabase/migrations/20260922000100_product_cnc_sheets.sql','utf8'));
 const actor=randomUUID(),product=randomUUID(),other=randomUUID(),backdropProduct=randomUUID();
 await db.query("select set_config('test.actor',$1,false)",[actor]);
 await db.query('insert into public.wc_shipping_products(id,product_name) values($1,$2),($3,$4),($5,$6)',[product,'Market Table',other,'Other Product',backdropProduct,'Plane Arch Backdrop']);
 const parts=[{id:'side-panel',name:'Side panel'}];
 const saved=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,null)) value',[product,'Birch sheet',parts,'Cut along grain'])).rows[0].value;
 assert.equal(saved.product_id,product);assert.deepEqual(saved.parts,parts);assert.equal(saved.comment,'Cut along grain');
 await assert.rejects(async()=>{await db.query('select public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,null)',[product,'Duplicate',[], '']);},/duplicate key/);
 await assert.rejects(async()=>{await db.query('select public.wc_save_product_cnc_sheet($1,$2,2,$3,$4,$5,$6)',[saved.id,other,'Moved',[], '',saved.revision]);},/changed/);
 await assert.rejects(async()=>{await db.query('select public.wc_save_product_cnc_sheet($1,$2,2,$3,$4,$5,$6)',[saved.id,product,'Changed',[], '',randomUUID()]);},/changed/);
 const updated=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet($1,$2,2,$3,$4,$5,$6)) value',[saved.id,product,'Second sheet',parts,'Revised',saved.revision])).rows[0].value;
 assert.equal(updated.sheet_number,2);assert.notEqual(updated.revision,saved.revision);
 const objectPath=`${actor}/${randomUUID()}`;
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('cnc-files',$1,$2)",[objectPath,{size:123}]);
 await assert.rejects(async()=>{await db.query('select public.wc_attach_product_cnc_file($1,$2,$3,123,$4)',[saved.id,objectPath,'wrong.nc',updated.revision]);},/Invalid or missing TAP/);
 await assert.rejects(async()=>{await db.query('select public.wc_attach_product_cnc_file($1,$2,$3,124,$4)',[saved.id,objectPath,'cut.tap',updated.revision]);},/Invalid or missing TAP/);
 const attached=(await db.query('select to_jsonb(public.wc_attach_product_cnc_file($1,$2,$3,123,$4)) value',[saved.id,objectPath,'cut.tap',updated.revision])).rows[0].value;
 assert.equal(attached.filename,'cut.tap');assert.equal(attached.object_path,objectPath);
 await assert.rejects(async()=>{await db.query('select public.wc_attach_product_cnc_file($1,$2,$3,123,$4)',[saved.id,objectPath,'cut.tap',updated.revision]);},/changed/);
 await db.exec('set role authenticated');
 assert.equal((await db.query('select count(*)::int n from public.wc_product_cnc_sheets')).rows[0].n,1);
 await assert.rejects(async()=>{await db.query("update public.wc_product_cnc_sheets set name='bypass'");},/permission denied/);
 assert.equal((await db.query("select public.wc_save_product_cnc_sheet($1,$2,2,'Allowed',$3,'', $4) is not null ok",[saved.id,product,parts,attached.revision])).rows[0].ok,true);
 await db.exec('reset role');
 const material=randomUUID(),inactive=randomUUID();
 await db.query('insert into public.wc_materials values($1,$2,$3,true),($4,$5,$6,false)',[material,'Birch plywood','sheet',inactive,'Retired MDF','sheet']);
 await db.exec(await readFile('supabase/migrations/20260922000200_product_cnc_sheet_material.sql','utf8'));
 assert.equal((await db.query('select material_id from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0].material_id,null);
 assert.equal((await db.query("select to_regprocedure('public.wc_save_product_cnc_sheet(uuid,uuid,integer,text,jsonb,text,uuid)') is null gone")).rows[0].gone,true);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet(null,$1,3,$2,$3,$4,null,null)',[product,'No material',parts,'']),/Choose an active material/);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet(null,$1,3,$2,$3,$4,$5,null)',[product,'Inactive material',parts,'',inactive]),/Choose an active material/);
 const current=(await db.query('select revision from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0];
 const withMaterial=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet($1,$2,2,$3,$4,$5,$6,$7)) value',[saved.id,product,'Cutting sheet',parts,'Keep comment',material,current.revision])).rows[0].value;
 assert.equal(withMaterial.material_id,material);assert.equal(withMaterial.name,'Cutting sheet');
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet($1,$2,2,$3,$4,$5,$6,$7)',[saved.id,product,'Wrong',parts,'',inactive,withMaterial.revision]),/Choose an active material/);
 await assert.rejects(async()=>db.query('delete from public.wc_materials where id=$1',[material]),/foreign key/);
 await db.exec('set role authenticated');
 assert.equal((await db.query('select material_id from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0].material_id,material);
 await assert.rejects(async()=>db.query('update public.wc_product_cnc_sheets set material_id=$1',[inactive]),/permission denied/);
 await db.exec('reset role');
 await db.exec(await readFile('supabase/migrations/20260922000300_product_cnc_crc3d_file.sql','utf8'));
 assert.equal((await db.query('select filename from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0].filename,'cut.tap');
 const crcPath=`${actor}/${randomUUID()}`;
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('cnc-files',$1,$2)",[crcPath,{size:321}]);
 await assert.rejects(async()=>db.query('select public.wc_attach_product_cnc_file($1,$2,$3,321,$4)',[saved.id,crcPath,'cut.tap',withMaterial.revision]),/Invalid or missing CRC3D/);
 await db.exec('set role authenticated');
 const crc=(await db.query('select to_jsonb(public.wc_attach_product_cnc_file($1,$2,$3,321,$4)) value',[saved.id,crcPath,'cut.crc3d',withMaterial.revision])).rows[0].value;
 assert.equal(crc.filename,'cut.crc3d');assert.equal(crc.object_path,crcPath);
 await db.exec('reset role');
 await db.exec(await readFile('supabase/migrations/20260922000400_product_cnc_crv3d_file.sql','utf8'));
 assert.equal((await db.query('select filename from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0].filename,'cut.crc3d');
 const crvPath=`${actor}/${randomUUID()}`;
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('cnc-files',$1,$2)",[crvPath,{size:456}]);
 await assert.rejects(async()=>db.query('select public.wc_attach_product_cnc_file($1,$2,$3,456,$4)',[saved.id,crvPath,'cut.crc3d',crc.revision]),/Invalid or missing CRV3D/);
 await db.exec('set role authenticated');
 const crv=(await db.query('select to_jsonb(public.wc_attach_product_cnc_file($1,$2,$3,456,$4)) value',[saved.id,crvPath,'cut.crv3d',crc.revision])).rows[0].value;
 assert.equal(crv.filename,'cut.crv3d');assert.equal(crv.object_path,crvPath);
 await db.exec('reset role');
 const oldBackdrop=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,$5,null)) value',[backdropProduct,'Old unassigned sheet',parts,'Re-enter later',material])).rows[0].value;
 await db.exec(await readFile('supabase/migrations/20260922000500_product_cnc_backdrop_folding.sql','utf8'));
 assert.equal((await db.query('select count(*)::int n from public.wc_product_cnc_sheets where product_id=$1',[backdropProduct])).rows[0].n,0);
 assert.equal((await db.query('select count(*)::int n from public.wc_product_cnc_sheets where id=$1',[saved.id])).rows[0].n,1);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,$5,null,null)',[backdropProduct,'Missing option',parts,'',material]),/correct CNC folding option/);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet(null,$1,3,$2,$3,$4,$5,$6,null)',[product,'Wrong option',parts,'',material,'foldable']),/correct CNC folding option/);
 const folded=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,$5,$6,null)) value',[backdropProduct,'Foldable sheet',parts,'',material,'foldable'])).rows[0].value;
 const flat=(await db.query('select to_jsonb(public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,$5,$6,null)) value',[backdropProduct,'Non-foldable sheet',parts,'',material,'nonfoldable'])).rows[0].value;
 assert.equal(folded.sheet_number,flat.sheet_number);assert.notEqual(folded.id,flat.id);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet($1,$2,1,$3,$4,$5,$6,$7,$8)',[folded.id,backdropProduct,'Wrong tab',parts,'',material,'nonfoldable',folded.revision]),/another folding option/);
 await assert.rejects(async()=>db.query('select public.wc_save_product_cnc_sheet(null,$1,1,$2,$3,$4,$5,$6,null)',[backdropProduct,'Duplicate',parts,'',material,'foldable']),/duplicate key/);
 await db.exec('set role authenticated');
 await assert.rejects(async()=>db.query("update public.wc_product_cnc_sheets set folding='nonfoldable' where id=$1",[folded.id]),/permission denied/);
 await db.exec('reset role');
 assert.notEqual(oldBackdrop.id,folded.id);
 console.log('CNC cutting sheets: historical files, Backdrop folding isolation and re-entry, material, revisions and RLS passed.');
}catch(error){console.error(error.message,error.where||'',error.position||'');process.exitCode=1;}finally{await db.close();}
