export interface LogoPanel { width:number; height:number; inset:number; }
export interface LogoPlacement { png:string; name:string; ratio:number; x:number; y:number; width:number; }
export const logoHeight=(logo:LogoPlacement)=>logo.width/logo.ratio;
export function fitLogo(panel:LogoPanel,logo:LogoPlacement):LogoPlacement {
 const width=Math.max(1,Math.min(logo.width,panel.width-2*panel.inset,(panel.height-2*panel.inset)*logo.ratio));
 return {...logo,width,x:Math.max(panel.inset,Math.min(logo.x,panel.width-panel.inset-width)),y:Math.max(panel.inset,Math.min(logo.y,panel.height-panel.inset-width/logo.ratio))};
}
export function centreLogo(panel:LogoPanel,logo:LogoPlacement):LogoPlacement {
 const fitted=fitLogo(panel,logo);return {...fitted,x:(panel.width-fitted.width)/2,y:(panel.height-logoHeight(fitted))/2};
}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function logoDrawingSvg(panel:LogoPanel,placement:LogoPlacement):string {
 const logo=fitLogo(panel,placement),h=logoHeight(logo),r=(v:number)=>Math.round(v*10)/10;
 const line=(x1:number,y1:number,x2:number,y2:number,label:string)=>`<g stroke="#526172" stroke-width="1"><path d="M${x1},${y1}L${x2},${y2}" marker-start="url(#arrow)" marker-end="url(#arrow)"/></g><text x="${(x1+x2)/2}" y="${(y1+y2)/2-8}" text-anchor="middle" font-size="18">${label}</text>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${panel.width+180}mm" height="${panel.height+180}mm" viewBox="-90 -90 ${panel.width+180} ${panel.height+180}"><title>Front panel logo placement — dimensions in mm</title><defs><marker id="arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M10 0L0 5L10 10" fill="none" stroke="#526172"/></marker></defs><rect x="-90" y="-90" width="${panel.width+180}" height="${panel.height+180}" fill="white"/><g font-family="Arial,sans-serif" fill="#263241"><text x="0" y="-60" font-size="20">FRONT · mm</text><rect width="${panel.width}" height="${panel.height}" fill="#f4f3f1" stroke="#263241" stroke-width="2"/>${panel.inset?`<rect x="${panel.inset}" y="${panel.inset}" width="${panel.width-2*panel.inset}" height="${panel.height-2*panel.inset}" fill="white" stroke="#9aabbc" stroke-dasharray="5 5"/>`:''}<image href="${escape(logo.png)}" x="${logo.x}" y="${logo.y}" width="${logo.width}" height="${h}"/><rect x="${logo.x}" y="${logo.y}" width="${logo.width}" height="${h}" fill="none" stroke="#1884e8" stroke-dasharray="4 4"/>${line(0,-25,panel.width,-25,String(r(panel.width)))}${line(0,panel.height+35,logo.x,panel.height+35,String(r(logo.x)))}${line(logo.x,panel.height+65,logo.x+logo.width,panel.height+65,String(r(logo.width)))}<g transform="translate(-35 ${panel.height/2}) rotate(-90)"><text text-anchor="middle" font-size="18">${r(panel.height)}</text></g><g transform="translate(${panel.width+35} ${logo.y/2}) rotate(-90)"><text text-anchor="middle" font-size="18">${r(logo.y)}</text></g><path d="M${panel.width+15} 0H${panel.width+25}V${logo.y}H${panel.width+15}" fill="none" stroke="#526172"/><g transform="translate(${panel.width+65} ${logo.y+h/2}) rotate(-90)"><text text-anchor="middle" font-size="18">${r(h)}</text></g><path d="M${panel.width+45} ${logo.y}H${panel.width+55}V${logo.y+h}H${panel.width+45}" fill="none" stroke="#526172"/></g></svg>`;
}
